data:
  dataset_name: 'temperature.npy'
  image_folder: /u00/arquivos_compartilhados/green_lab/climate_data/reanalysis-era5-land/
  patch_size: 11
  patch_stride: 8
  n_hr_views: 2
  n_lr_views: 6
  crop_sizes: [11, 8]
  min_scales: [0.8, 0.2]
  max_scales: [1.0, 0.5] 
training:
  device: 'cuda'
  backbone_model: 'resnet50'  
  n_features_swav: 128
  batch_size: 512
  n_prototypes: 15
  learning_rate: 0.0001
  sinkhorn_epsilon: 0.03
  max_patience: 2
  min_epochs: 5
  checkpoints_file_path: /u00/arquivos_compartilhados/green_lab/era_land_parana_checkpoints/
  weights_file_name: None
  low_info_thresh: None
  adjust_scale: False
  filter_data: False